/*
 * =====================================================================================
 * 
 *     Modulename:
 *       Filename:  maibu_bitmap_base.h
 *
 *    Description:  绯荤粺搴旂敤浣跨敤鐨勫熀鏈浘鏍囪祫婧�
 *    Corporation:
 * 
 *         Author:  gliu (), gliu@damaijiankang.com
 *        Created:  2014骞�12鏈�24鏃� 10鏃�04鍒�00绉�
 *
 * =====================================================================================
 */

#ifndef _RES_BITMAP_BASE_H

#define  RES_BITMAP_CLOCK_S				5001
#define  RES_BITMAP_CLOCK_CASE_1	5002
#define  RES_BITMAP_CLOCK_CASE_2	5003
#define  RES_BITMAP_CLOCK_CREATE	5004
#define  RES_BITMAP_CLOCK_DELETE	5005

#define  RES_BITMAP_BATTERY_1		5006
#define  RES_BITMAP_BATTERY_2		5007
#define  RES_BITMAP_BATTERY_3		5008
#define  RES_BITMAP_BATTERY_4		5009
#define  RES_BITMAP_BATTERY_5		5010
#define  RES_BITMAP_BATTERY_6		5011
#define  RES_BITMAP_BATTERY_B		5012

#define  RES_BITMAP_CALLING_ANSWER	5013
#define  RES_BITMAP_CALLING_DECLINE	5014
#define  RES_BITMAP_CALLING_PHONE_S	5015
#define  RES_BITMAP_CALLING_SIDEBAR	5016

#define  RES_BITMAP_MENU_MUSIC_B	5021
#define  RES_BITMAP_MENU_MESSAGE_B	5020
#define  RES_BITMAP_MENU_CLOCK_B	5018
#define  RES_BITMAP_MENU_SETTING_B	5023
#define  RES_BITMAP_MENU_ACTIVE_B	5017
#define  RES_BITMAP_MENU_HOME_S		5019

#define  RES_BITMAP_MUSIC_MUSIC_S	5024
#define  RES_BITMAP_MUSIC_NEXT		5025
#define  RES_BITMAP_MUSIC_PLAY		5026
#define  RES_BITMAP_MUSIC_PREV		5027
#define  RES_BITMAP_MUSIC_SIDEBAR	5028

#define  RES_BITMAP_NOTIFY_EDGE_1	5029
#define  RES_BITMAP_NOTIFY_EDGE_2	5030
#define  RES_BITMAP_NOTIFY_EDGE_3	5031
#define  RES_BITMAP_NOTIFY_MESSAGE_S	5032
#define  RES_BITMAP_NOTIFY_SHADOW	5034
#define  RES_BITMAP_NOTIFY_MSG_2	5033

#define  RES_BITMAP_SETTING_ABOUT	5039
#define  RES_BITMAP_SETTING_BLE_1	5040
#define  RES_BITMAP_SETTING_BLE_2	5041
#define  RES_BITMAP_SETTING_DECLINE	5043
#define  RES_BITMAP_SETTING_DISPLAY	5044
#define  RES_BITMAP_SETTING_MOON	5047
#define  RES_BITMAP_SETTING_NOTIFY	5049
#define  RES_BITMAP_SETTING_RESTORE	5050
#define  RES_BITMAP_SETTING_SETTING_S	5051
#define  RES_BITMAP_SETTING_SHUTDOWN	5052
#define  RES_BITMAP_SETTING_SIDEBAR	5053
#define  RES_BITMAP_SETTING_TICK	5054
#define  RES_BITMAP_SETTING_TIMEDATE	5055
#define  RES_BITMAP_SETTING_MAOHAO	5046
#define  RES_BITMAP_SETTING_MSGDEL	5048
#define  RES_BITMAP_SETTING_DAYFRAME	5042
#define  RES_BITMAP_SETTING_YEARFRAME	5056
#define  RES_BITMAP_SETTING_HOURFRAME	5045

#define  RES_BITMAP_WATCHFACE_WEATHER_BG	5063
#define  RES_BITMAP_WATCHFACE_CLOUDY		5058
#define  RES_BITMAP_WATCHFACE_RAINY		5059
#define  RES_BITMAP_WATCHFACE_SNOW		5060
#define  RES_BITMAP_WATCHFACE_TEM		5061
#define  RES_BITMAP_WATCHFACE_CIRCLE_BG		5062

#define  RES_BITMAP_OTHER_ROUND_H	5035
#define  RES_BITMAP_OTHER_ROUND_S	5036
#define  RES_BITMAP_OTHER_SHADOW_1	5037
#define  RES_BITMAP_OTHER_SHADOW_2	5038

#endif
