/*
 * =====================================================================================
 * 
 *     Modulename:
 *       Filename:  res_user_bitmap.h
 *
 *    Description:  用户应用图片资源 
 *    Corporation:
 * 
 *         Author:  gliu (), gliu@damaijiankang.com
 *        Created:  2015年01月13日 19时32分00秒
 *
 * =====================================================================================
 */
#ifndef _RES_USER_BITMAP_H
#define _RES_USER_BITMAP_H

/*-------------航班管家-----------------*/

/*箭头*/
#define RES_BITMAP_FLIGHTS_ARROW_ICON		10000

/*黑白背景*/
#define RES_BITMAP_FLIGHTS_BG_INFO_ICON 	10001

/*无关注背景*/
#define RES_BITMAP_FLIGHTS_BG_NOFLIGHT_ICON 	10002

/*行李转盘*/
#define RES_BITMAP_FLIGHTS_CAROUSEL_ICON 	10003

/*爬升*/
#define RES_BITMAP_FLIGHTS_CLIMB_ICON 		10004

/*下降*/
#define RES_BITMAP_FLIGHTS_FALL_ICON 		10005

/*登机口*/
#define RES_BITMAP_FLIGHTS_GATE_ICON 		10006

/*水平*/
#define RES_BITMAP_FLIGHTS_LEVEL_ICON 		10007

/*飞机图标*/
#define RES_BITMAP_FLIGHTS_PLANE_ICON 		10008

/*航站楼*/
#define RES_BITMAP_FLIGHTS_TERMINAL_ICON 	10009



/*天气表盘图标*/
#define  RES_BITMAP_WATCHFACE_WEATHER_BG		5300	
#define  RES_BITMAP_WATCHFACE_WEATHER_CLOUDY		5301
#define  RES_BITMAP_WATCHFACE_WEATHER_FOG		5302
#define  RES_BITMAP_WATCHFACE_WEATHER_OVERCAST		5303
#define  RES_BITMAP_WATCHFACE_WEATHER_RAIN_1		5304
#define  RES_BITMAP_WATCHFACE_WEATHER_RAIN_2		5305
#define  RES_BITMAP_WATCHFACE_WEATHER_RAIN_3		5306
#define  RES_BITMAP_WATCHFACE_WEATHER_SNOW_1		5307
#define  RES_BITMAP_WATCHFACE_WEATHER_SNOW_2		5308
#define  RES_BITMAP_WATCHFACE_WEATHER_SNOW_3		5309
#define  RES_BITMAP_WATCHFACE_WEATHER_SUNNY		5310
#define  RES_BITMAP_WATCHFACE_WEATHER_NODATA		5311




/*----------------------汉字表盘-------------------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHFACE_CHINESE_BG	 	5330	

/*0图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_0	 	5331

/*1图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_1	 	5332	

/*2图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_2	 	5333	

/*3图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_3	 	5334	

/*4图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_4	 	5335	

/*5图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_5	 	5336	

/*6图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_6	 	5337	

/*7图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_7	 	5338	

/*8图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_8	 	5339	

/*9图片*/
#define RES_BITMAP_WATCHFACE_CHINESE_9	 	5340	





/*--------------------点点表盘-----------------------------------*/

/*背景图*/
#define RES_BITMAP_WATCHFACE_POINT_BG	 	5380	

/*0图片*/
#define RES_BITMAP_WATCHFACE_POINT_0	 	5381

/*1图片*/
#define RES_BITMAP_WATCHFACE_POINT_1	 	5382	

/*2图片*/
#define RES_BITMAP_WATCHFACE_POINT_2	 	5383	

/*3图片*/
#define RES_BITMAP_WATCHFACE_POINT_3	 	5384	

/*4图片*/
#define RES_BITMAP_WATCHFACE_POINT_4	 	5385	

/*5图片*/
#define RES_BITMAP_WATCHFACE_POINT_5	 	5386	

/*6图片*/
#define RES_BITMAP_WATCHFACE_POINT_6	 	5387	

/*7图片*/
#define RES_BITMAP_WATCHFACE_POINT_7	 	5388	

/*8图片*/
#define RES_BITMAP_WATCHFACE_POINT_8	 	5389	

/*9图片*/
#define RES_BITMAP_WATCHFACE_POINT_9	 	5390






/*--------------------钢印表盘-----------------------------------*/

/*背景图*/
#define RES_BITMAP_WATCHFACE_STEEL_BG	 	5400

/*0图片*/
#define RES_BITMAP_WATCHFACE_STEEL_0	 	5401

/*1图片*/
#define RES_BITMAP_WATCHFACE_STEEL_1	 	5402	

/*2图片*/
#define RES_BITMAP_WATCHFACE_STEEL_2	 	5403	

/*3图片*/
#define RES_BITMAP_WATCHFACE_STEEL_3	 	5404	

/*4图片*/
#define RES_BITMAP_WATCHFACE_STEEL_4	 	5405	

/*5图片*/
#define RES_BITMAP_WATCHFACE_STEEL_5	 	5406	

/*6图片*/
#define RES_BITMAP_WATCHFACE_STEEL_6	 	5407	

/*7图片*/
#define RES_BITMAP_WATCHFACE_STEEL_7	 	5408	

/*8图片*/
#define RES_BITMAP_WATCHFACE_STEEL_8	 	5409	

/*9图片*/
#define RES_BITMAP_WATCHFACE_STEEL_9	 	5410





/*------------------英文表盘--------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHFACE_ENGLISH_BG		5430


/*----------------卡地亚表盘------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHFACE_CARTIER_BG		5450
#define RES_BITMAP_WATCHFACE_CARTIER_CENTER		5451



/*----------------计数器----------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHAPP_COUNTER_BG		5470





/*--------------番茄钟-----------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHAPP_TOMATO_BG			5480
#define RES_BITMAP_WATCHAPP_TOMATO_RESTING		5481
#define RES_BITMAP_WATCHAPP_TOMATO_BREST		5482
#define RES_BITMAP_WATCHAPP_TOMATO_SMALLT1		5483
#define RES_BITMAP_WATCHAPP_TOMATO_SMALLT2		5484
#define RES_BITMAP_WATCHAPP_TOMATO_SMALLT3		5485
#define RES_BITMAP_WATCHAPP_TOMATO_SMALLT4		5486
#define RES_BITMAP_WATCHAPP_TOMATO_END			5487
#define RES_BITMAP_WATCHAPP_TOMATO_TOMATO		5488


/*-------------健康管家---------------------------*/
#define RES_BITMAP_HEALTH_BG				5500
#define RES_BITMAP_HEALTH_INTRO_1			5501
#define RES_BITMAP_HEALTH_INTRO_2			5502
#define RES_BITMAP_HEALTH_INTRO_3			5503
#define RES_BITMAP_HEALTH_INTRO_4			5504
#define RES_BITMAP_HEALTH_INTRO_5			5505
#define RES_BITMAP_HEALTH_LOGO				5506
#define RES_BITMAP_HEALTH_PAGE_1			5507
#define RES_BITMAP_HEALTH_PAGE_2			5508
#define RES_BITMAP_HEALTH_PAGE_3			5509
#define RES_BITMAP_HEALTH_PAGE_4			5510
#define RES_BITMAP_HEALTH_CALORIE			5511
#define RES_BITMAP_HEALTH_SPORT				5512
#define RES_BITMAP_HEALTH_STAND				5513
#define RES_BITMAP_HEALTH_STAND_ALARM			5514
#define RES_BITMAP_HEALTH_CUP				5515


/*----------计时器-----------*/
#define RES_BITMAP_TIMER_SYS_BELL			5550	
#define RES_BITMAP_TIMER_USER_BELL			5551
#define RES_BITMAP_TIMER_CHOOSE_OFF			5552	
#define RES_BITMAP_TIMER_CHOOSE_ON			5553
#define RES_BITMAP_TIMER_LOGO				5554
#define RES_BITMAP_TIMER_SET_BG				5555





/*-------------------*/
#define RES_BITMAP_SPORT_BG				10100


/*--------服务标签---------*/
#define RES_BITMAP_SERVICES_LABEL			10030


/*--------测试工具---------*/
#define RES_BITMAP_TESTING_TOOL_BLACK			10050
#define RES_BITMAP_TESTING_TOOL_WHITE			10051


/*-------长沙银行动态口令-------*/
#define RES_BITMAP_DYNAMIC_PASSWORD_BG	10200



/*--------七分钟锻炼-------*/
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_PROGRESS_BAR	10300
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION1	10301
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION2	10302
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION3	10303
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION4	10304
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION5	10305
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION6	10306
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION7	10307
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION8	10308
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION9	10309
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION10	10310
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION11	10311
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ACTION12	10312
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_REST		10313
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_ICON		10314
#define RES_BITMAP_WATCHAPP_SEVEN_SPORTS_END_BMP	10315


/*比赛计分器*/
#define RES_BITMAP_WATCHAPP_COUNT_SCORE_BG_BMP				10330
#define RES_BITMAP_WATCHAPP_COUNT_SCORE_INTRO_BMP			10331
#define RES_BITMAP_WATCHAPP_COUNT_SCORE_CLEAR_BMP				10332


/*秒表*/
#define RES_BITMAP_WATCHAPP_STOPWATCH_SIDE_BG_BMP				10350	
#define RES_BITMAP_WATCHAPP_STOPWATCH_SIDE_COUNT_BMP				10351	
#define RES_BITMAP_WATCHAPP_STOPWATCH_SIDE_PLAY_BMP				10352	
#define RES_BITMAP_WATCHAPP_STOPWATCH_SIDE_PAUSE_BMP				10353	
#define RES_BITMAP_WATCHAPP_STOPWATCH_SIDE_CLEAR_BMP				10354


/*跑步助手*/
#define RES_BITMAP_WATCHAPP_RUN_HELPER_INTRO_BMP				10400
#define RES_BITMAP_WATCHAPP_RUN_HELPER_LABEL_BMP				10401
#define RES_BITMAP_WATCHAPP_RUN_HELPER_SIDE_BG_BMP				10402
#define RES_BITMAP_WATCHAPP_RUN_HELPER_SIDE_PLAY_BMP				10403
#define RES_BITMAP_WATCHAPP_RUN_HELPER_SIDE_PAUSE_BMP				10404
#define RES_BITMAP_WATCHAPP_RUN_HELPER_FINISH_BMP				10405


/*极简表盘*/
#define RES_BITMAP_WATCHFACE_SIMPLE_BG						10500
#define RES_BITMAP_WATCHFACE_SIMPLE_0						10501
#define RES_BITMAP_WATCHFACE_SIMPLE_1						10502
#define RES_BITMAP_WATCHFACE_SIMPLE_2						10503
#define RES_BITMAP_WATCHFACE_SIMPLE_3						10504
#define RES_BITMAP_WATCHFACE_SIMPLE_4						10505
#define RES_BITMAP_WATCHFACE_SIMPLE_5						10506
#define RES_BITMAP_WATCHFACE_SIMPLE_6						10507
#define RES_BITMAP_WATCHFACE_SIMPLE_7						10508
#define RES_BITMAP_WATCHFACE_SIMPLE_8						10509
#define RES_BITMAP_WATCHFACE_SIMPLE_9						10510


/*电路表盘*/
#define RES_BITMAP_WATCHFACE_CIRCUIT_BG						10600
#define RES_BITMAP_WATCHFACE_CIRCUIT_0						10601
#define RES_BITMAP_WATCHFACE_CIRCUIT_1						10602
#define RES_BITMAP_WATCHFACE_CIRCUIT_2						10603
#define RES_BITMAP_WATCHFACE_CIRCUIT_3						10604
#define RES_BITMAP_WATCHFACE_CIRCUIT_4						10605
#define RES_BITMAP_WATCHFACE_CIRCUIT_5						10606
#define RES_BITMAP_WATCHFACE_CIRCUIT_6						10607
#define RES_BITMAP_WATCHFACE_CIRCUIT_7						10608
#define RES_BITMAP_WATCHFACE_CIRCUIT_8						10609
#define RES_BITMAP_WATCHFACE_CIRCUIT_9						10610


/*乔布斯*/
#define RES_BITMAP_WATCHFACE_JOBS_BG						10620

/*海绵宝宝*/
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_1					10700
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_2					10701
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_3					10702
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_4					10703
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_5					10704
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_6					10705
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_7					10706
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_8					10707
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_9					10708
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_10					10709
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_11					10710
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_12					10711
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_13					10712
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_14					10713
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_15					10714
#define RES_BITMAP_WATCHFACE_SPONGEBOB_BG_16					10715
#define RES_BITMAP_WATCHFACE_SPONGEBOB_0					10716
#define RES_BITMAP_WATCHFACE_SPONGEBOB_1					10717
#define RES_BITMAP_WATCHFACE_SPONGEBOB_2					10718
#define RES_BITMAP_WATCHFACE_SPONGEBOB_3					10719
#define RES_BITMAP_WATCHFACE_SPONGEBOB_4					10720
#define RES_BITMAP_WATCHFACE_SPONGEBOB_5					10721
#define RES_BITMAP_WATCHFACE_SPONGEBOB_6					10722
#define RES_BITMAP_WATCHFACE_SPONGEBOB_7					10723
#define RES_BITMAP_WATCHFACE_SPONGEBOB_8					10724
#define RES_BITMAP_WATCHFACE_SPONGEBOB_9					10725
#define RES_BITMAP_WATCHFACE_SPONGEBOB_MAOHAO					10726


/*个性表盘*/
#define RES_BITMAP_WATCHFACE_SPECIFIC_T0					10800
#define RES_BITMAP_WATCHFACE_SPECIFIC_T1					10801
#define RES_BITMAP_WATCHFACE_SPECIFIC_T2					10802
#define RES_BITMAP_WATCHFACE_SPECIFIC_T3					10803
#define RES_BITMAP_WATCHFACE_SPECIFIC_T4					10804
#define RES_BITMAP_WATCHFACE_SPECIFIC_T5					10805
#define RES_BITMAP_WATCHFACE_SPECIFIC_T6					10806
#define RES_BITMAP_WATCHFACE_SPECIFIC_T7					10807
#define RES_BITMAP_WATCHFACE_SPECIFIC_T8					10808
#define RES_BITMAP_WATCHFACE_SPECIFIC_T9					10809
#define RES_BITMAP_WATCHFACE_SPECIFIC_T10					10810
#define RES_BITMAP_WATCHFACE_SPECIFIC_D0					10811
#define RES_BITMAP_WATCHFACE_SPECIFIC_D1					10812
#define RES_BITMAP_WATCHFACE_SPECIFIC_D2					10813
#define RES_BITMAP_WATCHFACE_SPECIFIC_D3					10814
#define RES_BITMAP_WATCHFACE_SPECIFIC_D4					10815
#define RES_BITMAP_WATCHFACE_SPECIFIC_D5					10816
#define RES_BITMAP_WATCHFACE_SPECIFIC_D6					10817
#define RES_BITMAP_WATCHFACE_SPECIFIC_D7					10818
#define RES_BITMAP_WATCHFACE_SPECIFIC_D8					10819
#define RES_BITMAP_WATCHFACE_SPECIFIC_D9					10820
#define RES_BITMAP_WATCHFACE_SPECIFIC_D10					10821
#define RES_BITMAP_WATCHFACE_SPECIFIC_BG					10822


/*骑行*/
#define RES_BITMAP_WATCHFACE_BICYCLE_TEXT					10850


#define RES_BITMAP_TEST1	8000



#endif
