/*
 * =====================================================================================
 * 
 *     Modulename:
 *       Filename:  res_bitmap_base.h
 *
 *    Description:  系统应用使用的基本图标资源
 *    Corporation:
 * 
 *         Author:  gliu (), gliu@damaijiankang.com
 *        Created:  2014年12月24日 10时04分00秒
 *
 * =====================================================================================
 */

#ifndef _RES_BITMAP_BASE_H


/*闹钟图标*/
#define  RES_BITMAP_CLOCK_S		5000
#define  RES_BITMAP_CLOCK_CASE_1	5001
#define  RES_BITMAP_CLOCK_CASE_2	5002
#define  RES_BITMAP_CLOCK_CREATE	5003
#define  RES_BITMAP_CLOCK_DELETE	5004


/*电池图标*/
#define  RES_BITMAP_BATTERY_1		5020
#define  RES_BITMAP_BATTERY_2		5021
#define  RES_BITMAP_BATTERY_3		5022
#define  RES_BITMAP_BATTERY_4		5023
#define  RES_BITMAP_BATTERY_5		5024
#define  RES_BITMAP_BATTERY_6		5025
#define  RES_BITMAP_BATTERY_B		5026


/*电话接听图标*/
#define  RES_BITMAP_CALLING_ANSWER	5040
#define  RES_BITMAP_CALLING_DECLINE	5041
#define  RES_BITMAP_CALLING_PHONE_S	5042
#define  RES_BITMAP_CALLING_SIDEBAR	5043


/*系统菜单图标*/
#define  RES_BITMAP_MENU_MUSIC_B	5060
#define  RES_BITMAP_MENU_MESSAGE_B	5061
#define  RES_BITMAP_MENU_CLOCK_B	5062
#define  RES_BITMAP_MENU_SETTING_B	5063
#define  RES_BITMAP_MENU_ACTIVE_B	5064
#define  RES_BITMAP_MENU_HOME_S		5065


/*音乐图标*/
#define  RES_BITMAP_MUSIC_MUSIC_S	5080
#define  RES_BITMAP_MUSIC_NEXT		5081
#define  RES_BITMAP_MUSIC_PLAY		5082
#define  RES_BITMAP_MUSIC_PREV		5083
#define  RES_BITMAP_MUSIC_SIDEBAR	5084


/*通知中心图标*/
#define  RES_BITMAP_NOTIFY_EDGE_1	5100
#define  RES_BITMAP_NOTIFY_EDGE_2	5101
#define  RES_BITMAP_NOTIFY_EDGE_3	5102
#define  RES_BITMAP_NOTIFY_MESSAGE_S	5103
#define  RES_BITMAP_NOTIFY_SHADOW	5104
#define  RES_BITMAP_NOTIFY_MSG_2	5105

/*设置图标*/
#define  RES_BITMAP_SETTING_ABOUT	5120
#define  RES_BITMAP_SETTING_BLE_1	5121
#define  RES_BITMAP_SETTING_BLE_2	5122
#define  RES_BITMAP_SETTING_DECLINE	5123
#define  RES_BITMAP_SETTING_DISPLAY	5124
#define  RES_BITMAP_SETTING_MOON	5125
#define  RES_BITMAP_SETTING_NOTIFY	5126
#define  RES_BITMAP_SETTING_RESTORE	5127
#define  RES_BITMAP_SETTING_SETTING_S	5128
#define  RES_BITMAP_SETTING_SHUTDOWN	5129
#define  RES_BITMAP_SETTING_SIDEBAR	5130
#define  RES_BITMAP_SETTING_TICK	5131
#define  RES_BITMAP_SETTING_TIMEDATE	5132
#define  RES_BITMAP_SETTING_MAOHAO	5133
#define  RES_BITMAP_SETTING_MSGDEL	5134
#define  RES_BITMAP_SETTING_DAYFRAME	5135
#define  RES_BITMAP_SETTING_YEARFRAME	5136
#define  RES_BITMAP_SETTING_HOURFRAME	5137
#define  RES_BITMAP_SETTING_CLEAR_NOTIFY	5138
#define  RES_BITMAP_SETTING_CLEAR_ALL		5139


/*指针表盘图标*/
#define  RES_BITMAP_WATCHFACE_CIRCLE_BG		5150	



/*状态图标*/
#define  RES_BITMAP_STATE_STARTING		5180
#define  RES_BITMAP_STATE_INSTALLING		5181
#define  RES_BITMAP_STATE_SHUTTING		5182
#define  RES_BITMAP_STATE_CHARGING		5183
#define  RES_BITMAP_STATE_BATTERY_0		5184
#define  RES_BITMAP_STATE_BATTERY_10		5185
#define  RES_BITMAP_STATE_BATTERY_20		5186
#define  RES_BITMAP_STATE_BATTERY_100		5187
#define  RES_BITMAP_STATE_NOBIND		5188
#define  RES_BITMAP_STATE_NOBIND_TEXT		5189
#define  RES_BITMAP_STATE_NOTIFY_BG		5190
#define  RES_BITMAP_STATE_RESTART		5191
#define  RES_BITMAP_STATE_FACTORY		5192


/*其他图标*/
#define  RES_BITMAP_OTHER_ROUND_H	5200
#define  RES_BITMAP_OTHER_ROUND_S	5201
#define  RES_BITMAP_OTHER_SHADOW_1	5202
#define  RES_BITMAP_OTHER_SHADOW_2	5203




/*----------------------月周日表盘----------------------------*/
/*背景图*/
#define RES_BITMAP_WATCHFACE_MWD_BG		5360


/*正规表盘*/
#define  RES_BITMAP_WATCHFACE_OFFICIAL_BG		5600	
#define  RES_BITMAP_WATCHFACE_OFFICIAL_CENTER		5601



/*蓝牙状态图标*/
#define RES_BITMAP_BLE_STATE_WRONG		5580
#define RES_BITMAP_BLE_STATE_CONNECTED		5581



/*长沙银行交易背景图片*/
#define RES_BITMAP_CHANGSHA_BANK_DEAL_IDENTIFY			8000
#define RES_BITMAP_CHANGSHA_BANK_DEAL_SUCC			8001
#define RES_BITMAP_CHANGSHA_BANK_DEAL_CANCEL			8002


/*正规表盘2*/
#define  RES_BITMAP_WATCHFACE_OFFICIAL_DATE_STEP_BG		5610	
#define  RES_BITMAP_WATCHFACE_OFFICIAL_DATE_STEP_STEP		5611



#endif
